### ISSUE TITLE
Are all the functionalities ready to be used?

### ISSUE THREAD

**Issue by bhavin2897** [DataShades/ckanext-search-tweaks#2]
While trying to add a did_you_mean feature to my CKAN instance, it seams the did_you_mean.html have a error. 

I have added it to the search_form.html from ckan snippets. 

Apart from that I would like to know wheather all the functionality on READ.ME are ready to be used?  It seems some of them are broken.

How can I check/test them?

**Comment by smotornyuk** [comment]
All the features are functioning properly and I'm using them in a couple of projects. But documentation is outdated and I just have to time to align it with the current setting unfortunately
